# Generated by Django 4.0 on 2022-03-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog',
            new_name='blogpost',
        ),
    ]
