# Generated by Django 4.0 on 2022-03-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_alter_blogpost_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
