# Generated by Django 4.0 on 2022-03-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_alter_blogpost_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='catagory',
            field=models.CharField(choices=[('author', 'author'), ('My_story', 'My_story')], max_length=200, null=True),
        ),
    ]
