# Generated by Django 4.0 on 2022-03-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_blogpost_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y'),
        ),
    ]
